name: build

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build-vita:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set outputs
        id: outputs
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)" && echo "::set-output name=branch::${GITHUB_REF##*/}"
      - name: Setup dependencies
        run: sudo apt-get install -y make cmake
      - name: Setup VitaSDK
        run: |
          export VITASDK=/usr/local/vitasdk && export PATH=$VITASDK/bin:$PATH && git clone https://github.com/vitasdk/vdpm && cd vdpm && ./bootstrap-vitasdk.sh && ./install-all.sh
      - name: Build
        run: |
          export VITASDK=/usr/local/vitasdk && export PATH=$VITASDK/bin:$PATH && cmake . && make Terri-Fried.vpk
      - name: Upload Vita Package
        uses: actions/upload-artifact@v2
        with:
          path: ./Terri-Fried.vpk
          name: Terri-Fried-${{ steps.outputs.outputs.branch }}-${{ steps.outputs.outputs.sha_short }}.vpk
